### PR TITLE
Fix #28

### LINKED ISSUE #20: Custom toml files not working
image

### LINKED ISSUE #28: In some cases, the hint is not available
If we define it in the Toml file using the following approach, Gradle is unable to generate the `3dmap` field. Therefore, we must use `libs.amap.get3dmap()` to retrieve it, which causes the hint to not work. 

```toml
amap-3dmap = "com.amap.api:3dmap:9.4.0"
```

```kotlin
implementation(libs.amap.get3dmap())
```
WX20230706-102503
Additionally, using bundles also seems to be ineffective.
WX20230706-102931

### PR DESCRIPTION
**Pull request by 5peak2me**

### CODE REVIEW

**Comment by 5peak2me** [comment]
Did you consider merging this PR, and if so, could you release an update?

**Comment by F43nd1r** [comment]
Sorry for the late response. Please separate the fix for #28 from the fix for #20. Your fix for #20 is not generic and won't be upstreamed in its current form, but the fix for #28 looks mostly okay. 

Please also consider my latest comment here https://github.com/F43nd1r/gradle-version-catalogs-intellij-plugin/issues/20#issuecomment-1621481672

**Comment by 5peak2me** [comment]
@F43nd1r done

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt [hunk 1]
```diff
@@ -15,11 +15,18 @@ private const val BUNDLE_SUPPLIER = "org.gradle.api.internal.catalog.ExternalMod
...
 
+@Suppress("SpellCheckingInspection")
 data class Accessor(val element: PsiElement, val id: String, val type: VCElementType) {
     companion object {
         fun find(element: PsiElement): Accessor? {
-            val returnType = element.lastChild.references.map { it.resolve() }.firstIsInstanceOrNull<PsiMethod>()?.returnType ?: return null
-            val segments by lazy { element.text.replace(Regex("\\s+"), "").split(".").drop(1) }
+            val references = if (element.lastChild.references.mapNotNull(PsiReference::resolve).isEmpty()) {
+                element.lastChild.firstChild.references
+            } else element.lastChild.references
```
Comment (F43nd1r) [inline src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt:24]: Can you explain why the references code changed?

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt [hunk 2]
```diff
@@ -15,11 +15,18 @@ private const val BUNDLE_SUPPLIER = "org.gradle.api.internal.catalog.ExternalMod
...
+            val returnType = references.map { it.resolve() }.firstIsInstanceOrNull<PsiMethod>()?.returnType ?: return null
+            val segments by lazy { element.text.replace(Regex("\\s+"), "").split(".").drop(1)
+                // e.g. libs.map.get3dmap() -> [libs, map, get3dmap()] -> [map, get3dmap()] -> [map, 3dmap]
+                .map { it.removePrefix("get").removeSuffix("()") }
```
Comment (F43nd1r) [inline src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt:28]: This should only remove the get prefix if it is actually a function call, otherwise libraries starting with get will break.

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/inlayhints/VersionCatalogInlayHintsProvider.kt [hunk 3]
```diff
@@ -45,6 +45,7 @@ class VersionCatalogInlayHintsProvider : InlayHintsProvider<NoSettings> {
                                         VCElementType.LIBRARY -> resolvePotentiallyTabledDefinition(referencedValue, "module")
                                         VCElementType.VERSION -> referencedValue.text?.unquote()
                                         VCElementType.PLUGIN -> resolvePotentiallyTabledDefinition(referencedValue, "id")
+                                        VCElementType.BUNDLE -> resolveBundlesDefinition(referencedValue)
```
Comment (F43nd1r) [inline src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/inlayhints/VersionCatalogInlayHintsProvider.kt:48]: Bundles can be very large, not sure if inlay hints are the best idea here. Maybe with cutoff and ellipsis after 3 or 5 or something?

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt (hunk 1 above)
Comment (5peak2me) [reply src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt:24]: This change is mainly due to the fact that `element.lastChild.references.map { it.resolve() }` is always null when using definitions such as the `map-3dmap` type. because normally `element.lastChild` for `libs.x.y.z` is `z`, but `libs.map.get3dmap()` is `()` . and it is not possible to call `references` to get the result.

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt (hunk 2 above)
Comment (5peak2me) [reply src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt:28]: I have tested various use cases such as `libs.map.get3dmap`, `libs.get3dmap().map`, `libs.get3dmap().get2dmap()`.it works great.At the moment I don't know how to write test cases for Inlay Hint. Maybe later I will actively look for options to write unit test cases.

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/inlayhints/VersionCatalogInlayHintsProvider.kt (hunk 3 above)
Comment (5peak2me) [reply src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/inlayhints/VersionCatalogInlayHintsProvider.kt:48]: Yeah！you're right. I'll make a samll change.

File: src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt (hunk 2 above)
Comment (5peak2me) [reply src/main/kotlin/com/faendir/intellij/gradleVersionCatalogs/kotlin/Accessor.kt]: I made some adjustments and it's working properly.
WX20230725-182857
WX20230725-182357
